Support for .NET Framework 4.8.1 & .NET 7
NuGetPackageExplorer/NuGetPackageExplorer pull request #1556
Opened 2022-10-30 09:45 UTC by Wagnerp

* Implement #1555

2022-12-06 18:33 UTC, clairernovotny commented on PackageExplorer/PackageViewer.xaml.cs
> +                        "v5.0-windows", "net5.0-windows7.0",
Why is the 7.0 being added to windows here?

2022-12-14 20:09 UTC, clairernovotny commented
Looks good overall except for adding the `7.0` to `windows` as per the comment above. not sure why?

2022-12-14 20:16 UTC, clairernovotny requested changes
Please change `windows7.0` back to `windows`

2022-12-15 09:21 UTC, Wagnerp commented
> Please change `windows7.0` back to `windows`

@clairernovotny Reinstated for `.NET 5`, _but_ you can't do the same with >= .NET 6, otherwise it'll fail to save the package. See #1566 for details.

2023-01-07 16:40 UTC, Wagnerp commented
Update, removed `-windows7.0` -> `-windows`

2023-02-25 09:27 UTC, Wagnerp commented
Added .NET 8 to the list

2023-07-21 12:03 UTC, merged